[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# Mostrar los nombres de todos los tests ejecutados
addopts =
    -v
    --tb=short
    --no-header

# Ignorar warnings de librerías de terceros
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
